variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - check
  - build

image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner

lint:
  stage: check
  interruptible: true
  script:
    - >
        nix-shell -I nixpkgs=./pkgs.nix --packages nodejs --run '
        npm install;
        npm run lint;
        '

test:
  stage: check
  interruptible: true
  script:
    - >
        nix-shell -I nixpkgs=./pkgs.nix --packages nodejs --run '
        npm install;
        npm run test;
        '

nix-dry:
  stage: check
  interruptible: true
  script:
    - nix-build -v -v --dry-run ./release.nix --attr application
    - nix-build -v -v --dry-run ./release.nix --attr docker

nix:
  stage: build
  interruptible: true
  script:
    - >
        nix-build ./release.nix
        --attr application
        --attr docker
  only:
    - master
