variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

stages:
  - check
  - build

before_script:
  - node --version
  - npm install

prettier:
  stage: check
  image: node:12
  script:
    - npm run lint

jest:
  stage: check
  image: node:12
  script:
    - npm run test

nix-dry:
  stage: check
  image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner
  script:
    - nix-shell --packages nodejs-12_x.all --run "nix-build -v -v --dry-run ./nix/default.nix"

npm-build:
  stage: build
  image: node:12
  script:
    - npm run build:library
    - npm run build:documentation

nix-build:
  stage: build
  image: registry.gitlab.com/matrixai/engineering/maintenance/gitlab-runner
  script:
    - nix-shell --packages nodejs-12_x.all --run "nix-build ./nix/default.nix -o result-0"

